# Generated by Django 5.1.1 on 2024-11-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0020_alter_residents_auth_user'),
        ('barangay', '0021_alter_outbreaks_purok'),
    ]

    operations = [
    ]
