# Generated by Django 5.1.1 on 2024-11-09 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0022_merge_20241108_1925'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_name', models.CharField(max_length=100)),
                ('announcement_description', models.TextField(null=True)),
                ('announcement_date', models.DateField(null=True)),
                ('announcement_time', models.TimeField(null=True)),
                ('announcement_type', models.CharField(max_length=100)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.personnel')),
                ('bhw_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.bhw')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
