# Generated by Django 5.1.1 on 2024-11-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0023_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbreaks',
            name='outbreak_type',
        ),
        migrations.AddField(
            model_name='outbreaks',
            name='fname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outbreaks',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
