# Generated by Django 5.1.1 on 2024-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0024_remove_outbreaks_outbreak_type_outbreaks_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbreaks',
            name='date',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
