# Generated by Django 5.1.1 on 2024-11-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0026_healthservice_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
    ]
