# Generated by Django 5.1.1 on 2024-11-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0027_remove_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
