# Generated by Django 5.1.1 on 2024-11-20 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0028_schedule_status_schedule_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('position', models.CharField(max_length=255)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='bns_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.bns'),
        ),
    ]
