# Generated by Django 5.1.1 on 2024-11-20 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0029_bns_accounts_bns_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bns',
            new_name='Bis',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='bns_id',
            new_name='bis_id',
        ),
    ]
