# Generated by Django 5.1.1 on 2024-11-23 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0032_healthadmin_accounts_ha_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=100)),
                ('notice_description', models.TextField(null=True)),
                ('notice_date', models.DateField(null=True)),
                ('notice_time', models.TimeField(null=True)),
                ('notice_type', models.CharField(max_length=100)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.personnel')),
                ('bhw_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.bhw')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
