# Generated by Django 5.1.1 on 2024-11-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0033_communitynotice_delete_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitynotice',
            old_name='notice_date',
            new_name='notice_EndDate',
        ),
        migrations.RenameField(
            model_name='communitynotice',
            old_name='notice_time',
            new_name='notice_EndTime',
        ),
        migrations.AddField(
            model_name='communitynotice',
            name='notice_StartDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='communitynotice',
            name='notice_StartTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='communitynotice',
            name='notice_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
