# Generated by Django 5.1.1 on 2024-11-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0034_rename_notice_date_communitynotice_notice_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitynotice',
            old_name='notice_EndDate',
            new_name='announcement_date',
        ),
        migrations.RenameField(
            model_name='communitynotice',
            old_name='notice_description',
            new_name='announcement_description',
        ),
        migrations.RenameField(
            model_name='communitynotice',
            old_name='notice_name',
            new_name='announcement_name',
        ),
        migrations.RenameField(
            model_name='communitynotice',
            old_name='notice_EndTime',
            new_name='announcement_time',
        ),
        migrations.RenameField(
            model_name='communitynotice',
            old_name='notice_type',
            new_name='announcement_type',
        ),
        migrations.RemoveField(
            model_name='communitynotice',
            name='notice_StartDate',
        ),
        migrations.RemoveField(
            model_name='communitynotice',
            name='notice_StartTime',
        ),
        migrations.RemoveField(
            model_name='communitynotice',
            name='notice_image',
        ),
    ]
