# Generated by Django 5.1.1 on 2024-11-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0035_rename_notice_enddate_communitynotice_announcement_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitynotice',
            old_name='announcement_date',
            new_name='notice_EndDate',
        ),
        migrations.RenameField(
            model_name='communitynotice',
            old_name='announcement_time',
            new_name='notice_EndTime',
        ),
        migrations.RenameField(
            model_name='communitynotice',
            old_name='announcement_description',
            new_name='notice_description',
        ),
        migrations.RenameField(
            model_name='communitynotice',
            old_name='announcement_name',
            new_name='notice_name',
        ),
        migrations.RenameField(
            model_name='communitynotice',
            old_name='announcement_type',
            new_name='notice_type',
        ),
        migrations.AddField(
            model_name='communitynotice',
            name='notice_StartDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='communitynotice',
            name='notice_StartTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='communitynotice',
            name='notice_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
