# Generated by Django 5.1.1 on 2024-11-23 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0035_remove_schedule_age_remove_schedule_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.residents'),
        ),
    ]
