# Generated by Django 5.1.1 on 2024-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0036_schedule_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
