# Generated by Django 5.1.1 on 2024-11-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0036_rename_announcement_date_communitynotice_notice_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitynotice',
            name='notice_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
