# Generated by Django 5.1.1 on 2024-11-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0037_residents_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhw',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bsi',
            name='age',
        ),
        migrations.RemoveField(
            model_name='healthadmin',
            name='age',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='residents',
            name='age',
        ),
    ]
