# Generated by Django 5.1.1 on 2024-11-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0038_alter_communitynotice_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotice',
            name='notice_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
