# Generated by Django 5.1.1 on 2024-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0038_remove_bhw_age_remove_bsi_age_remove_healthadmin_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='id_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
