# Generated by Django 5.1.1 on 2024-12-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0039_alter_communitynotice_notice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='officials_id',
        ),
    ]
