# Generated by Django 5.1.1 on 2024-11-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0039_residents_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbreaks',
            name='total_cases',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
