# Generated by Django 5.1.1 on 2024-11-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0041_alter_outbreaks_total_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbreaks',
            name='total_cases',
        ),
    ]
