# Generated by Django 5.1.1 on 2024-11-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0042_remove_outbreaks_total_cases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbreaks',
            old_name='severity',
            new_name='status',
        ),
    ]
