# Generated by Django 5.1.1 on 2024-11-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0043_rename_severity_outbreaks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbreaks',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
