# Generated by Django 5.1.1 on 2024-12-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0043_alter_residents_auth_user_alter_residents_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='schedule_end_time',
        ),
        migrations.AddField(
            model_name='request',
            name='service_requirements',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
