# Generated by Django 5.1.1 on 2024-12-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0044_remove_request_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='service_requirements',
        ),
        migrations.AddField(
            model_name='request',
            name='schedule_end_time',
            field=models.TimeField(null=True),
        ),
    ]
