# Generated by Django 5.1.1 on 2024-12-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0045_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='resident_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.residents'),
        ),
    ]
