# Generated by Django 5.1.1 on 2024-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0046_maintenance_resident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='bp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='kg',
            field=models.IntegerField(null=True),
        ),
    ]
