# Generated by Django 5.1.1 on 2024-12-03 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0047_maintenance_bp_maintenance_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='schedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.schedule'),
        ),
    ]
