# Generated by Django 5.1.1 on 2024-12-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0048_maintenance_schedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='bhw_id',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='user',
        ),
    ]
