# Generated by Django 5.1.1 on 2024-12-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0051_remove_maintenance_bhw_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='resident_id',
            new_name='resident',
        ),
    ]
