# Generated by Django 5.1.1 on 2024-12-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0052_rename_resident_id_maintenance_resident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='healthservice_id',
            new_name='bhwService',
        ),
    ]
