# Generated by Django 5.1.1 on 2024-12-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0053_rename_healthservice_id_maintenance_bhwservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='resident',
            new_name='resident_id',
        ),
    ]
