# Generated by Django 5.1.1 on 2024-12-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0054_rename_resident_maintenance_resident_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='resident_id',
            new_name='resident',
        ),
    ]
