# Generated by Django 5.1.1 on 2024-12-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0055_rename_resident_id_maintenance_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='resident',
        ),
    ]
