# Generated by Django 5.1.1 on 2024-12-06 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0058_schedule_bp_schedule_kg_schedule_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='kg',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('week', models.CharField(max_length=100, null=True)),
                ('kg', models.IntegerField(null=True)),
                ('bp', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('resident_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.residents')),
                ('schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.schedule')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
