# Generated by Django 5.1.1 on 2024-12-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0059_remove_schedule_bp_remove_schedule_kg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='schedule_id',
            new_name='schedule',
        ),
    ]
