# Generated by Django 5.1.1 on 2024-12-14 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0045_remove_request_service_requirements_and_more'),
        ('barangay', '0062_medicine'),
    ]

    operations = [
    ]
