# Generated by Django 5.1.1 on 2024-12-15 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0064_medicine_released_quantity_alter_residents_auth_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.schedule'),
        ),
    ]
