# Generated by Django 5.1.1 on 2024-12-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0065_medicine_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='maintenece_id',
            new_name='maintenance_id',
        ),
    ]
