# Generated by Django 5.1.1 on 2024-12-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0066_rename_maintenece_id_medicine_maintenance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='maintenance_id',
            new_name='maintenance',
        ),
    ]
