# Generated by Django 5.1.1 on 2024-12-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0068_schedule_book_img_schedule_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='baby_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
