# Generated by Django 5.1.1 on 2024-12-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0069_schedule_baby_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='week',
        ),
    ]
