# Generated by Django 5.1.1 on 2024-12-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0070_remove_schedule_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='book_img',
            new_name='img',
        ),
    ]
