# Generated by Django 5.1.1 on 2024-12-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0071_rename_book_img_schedule_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='img',
            new_name='image',
        ),
    ]
