# Generated by Django 5.1.1 on 2024-12-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0073_immunize'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunize',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='immunize',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='immunize',
            name='vaccine_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
