# Generated by Django 5.1.1 on 2024-12-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0074_immunize_date_immunize_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunize',
            name='vaccine_dose',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
