# Generated by Django 5.1.1 on 2024-12-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0066_request_status'),
        ('barangay', '0075_alter_immunize_vaccine_dose'),
    ]

    operations = [
    ]
