# Generated by Django 5.1.1 on 2024-12-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0076_merge_20241217_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Resident_id',
            new_name='resident',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='image',
        ),
    ]
