# Generated by Django 5.1.1 on 2024-12-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0077_rename_resident_id_request_resident_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunize',
            name='age',
        ),
        migrations.RemoveField(
            model_name='immunize',
            name='vaccine_description',
        ),
        migrations.RemoveField(
            model_name='immunize',
            name='vaccine_quantity',
        ),
        migrations.AddField(
            model_name='immunize',
            name='at_birth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='immunize',
            name='fifth_visit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='immunize',
            name='first_visit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='immunize',
            name='second_visit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='immunize',
            name='third_visit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ResidentImmunize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immunize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.immunize')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.schedule')),
            ],
        ),
    ]
