# Generated by Django 5.1.1 on 2024-12-28 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0077_household_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('birthdate', models.DateField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('position', models.CharField(max_length=255)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='secretary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.secretary'),
        ),
    ]
