# Generated by Django 5.1.1 on 2024-12-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0078_remove_immunize_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunize',
            name='date',
        ),
        migrations.RemoveField(
            model_name='immunize',
            name='resident_id',
        ),
        migrations.RemoveField(
            model_name='immunize',
            name='user',
        ),
    ]
