# Generated by Django 5.1.1 on 2024-12-23 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0081_alter_immunize_fifth_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunize',
            name='fifth_visit',
        ),
        migrations.RemoveField(
            model_name='immunize',
            name='first_visit',
        ),
        migrations.RemoveField(
            model_name='immunize',
            name='second_visit',
        ),
        migrations.RemoveField(
            model_name='immunize',
            name='third_visit',
        ),
        migrations.CreateModel(
            name='ImmunizeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_visit', models.DateField(blank=True, null=True)),
                ('second_visit', models.DateField(blank=True, null=True)),
                ('third_visit', models.DateField(blank=True, null=True)),
                ('fourth_visit', models.DateField(blank=True, null=True)),
                ('fifth_visit', models.DateField(blank=True, null=True)),
                ('immunize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.immunize')),
            ],
        ),
    ]
