# Generated by Django 5.1.1 on 2024-12-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0082_remove_immunize_fifth_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizedate',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.schedule'),
        ),
    ]
