# Generated by Django 5.1.1 on 2024-12-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0084_immunize_fifth_visit_immunize_first_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunize',
            name='fifth_visit',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='immunize',
            name='first_visit',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='immunize',
            name='fourth_visit',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='immunize',
            name='second_visit',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='immunize',
            name='third_visit',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
