# Generated by Django 5.1.1 on 2024-12-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0085_alter_immunize_fifth_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunize',
            name='fifth_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunize',
            name='first_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunize',
            name='fourth_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunize',
            name='second_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunize',
            name='third_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
