# Generated by Django 5.1.1 on 2024-12-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0087_alter_immunize_vaccine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunize',
            name='vaccine_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
