# Generated by Django 5.1.1 on 2024-12-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0089_remove_schedule_birth_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
