# Generated by Django 5.1.1 on 2024-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0090_schedule_date_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='month',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
