# Generated by Django 5.1.1 on 2024-12-31 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0078_secretary_accounts_secretary_id'),
        ('barangay', '0091_maintenance_month'),
    ]

    operations = [
    ]
