# Generated by Django 5.1.1 on 2024-12-31 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0092_merge_20241231_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='resident',
            new_name='Resident_id',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='service',
            new_name='service_id',
        ),
    ]
