# Generated by Django 5.1.1 on 2025-01-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0081_secretary_is_profile_complete_secretary_status'),
        ('barangay', '0093_rename_resident_request_resident_id_and_more'),
    ]

    operations = [
    ]
