# Generated by Django 5.1.1 on 2025-01-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0094_merge_20250118_0023'),
        ('barangay', '0095_remove_household_address'),
    ]

    operations = [
    ]
