# Generated by Django 5.1.1 on 2025-01-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0096_merge_20250118_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='bsi_id',
        ),
        migrations.RemoveField(
            model_name='healthadmin',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='ha_id',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='resident_id',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bsi',
        ),
        migrations.DeleteModel(
            name='HealthAdmin',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
