# Generated by Django 5.1.1 on 2025-01-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0097_remove_accounts_bsi_id_remove_healthadmin_auth_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residents',
            name='position',
        ),
    ]
