# Generated by Django 5.1.1 on 2025-02-19 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0098_remove_residents_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('sender_name', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('proof', models.ImageField(null=True, upload_to='images/')),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.residents')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.services')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
