# Generated by Django 5.1.1 on 2025-03-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0099_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
