# Generated by Django 5.1.1 on 2025-03-14 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0099_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widow', 'Widow')], max_length=20)),
                ('native_of', models.CharField(max_length=255)),
                ('purok', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('remarks', models.CharField(default='No Derogatory Record and is known of Good Moral Character', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
