# Generated by Django 5.1.1 on 2025-03-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0100_remove_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
