# Generated by Django 5.1.1 on 2025-03-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0100_barangayclearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayclearance',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='barangay.residents'),
        ),
        migrations.AlterField(
            model_name='barangayclearance',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barangayclearance',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widow', 'Widow')], max_length=20),
        ),
        migrations.AlterField(
            model_name='barangayclearance',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='barangayclearance',
            name='purok',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
