# Generated by Django 5.1.1 on 2025-03-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0101_alter_payment_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
        migrations.AddField(
            model_name='payment',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangay.request'),
        ),
    ]
