# Generated by Django 5.1.1 on 2025-03-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0104_rename_service_payment_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='service_id',
            new_name='service',
        ),
    ]
