# Generated by Django 5.1.1 on 2025-03-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0102_alter_residents_auth_user'),
        ('barangay', '0105_rename_service_id_payment_service'),
    ]

    operations = [
    ]
