from .admindashboard import *
from .models import *
from .views import *
from .residents import *
from .residentsched import *
from .models import *
from .views import *
from .Maintenance import *
from .approvedStatus import *
from .bsiSide import *
from .HealthAdminSide import *
from .verified_resident import *
from .outbreakStatus import *
from .bhwSide import *
from .medicine import *
from .maintenanceStatus import *
from .immunize import *
from .secretary import *
from .HSlanding import *